status/urls.py
from django.urls import path
from . import views

app_name = 'status'

urlpatterns = [
	path('', views.add_status, name='status'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('status.urls')),
    path('storyke7/',include('story7.urls')),
    path('books/', include('story8.urls')),
    path('story9/',include('story9.urls')),
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
	path('', views.addstatus, name='status'),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
	path('', views.list_books, name='books'),
	path('json/<str:keyword>/', views.process_json, name='process_json'),
] 

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('register/', views.register, name='register'),
	path('logout/', views.user_logout, name='logout'),
	path('', views.index, name='index'),
] 

status/models.py
from django.db import models

# Create your models here.
class StatusModel(models.Model):
	status = models.TextField() 
	time = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return self.status

story7/models.py
from django.db import models
from status.models import StatusModel
# Create your models here.
class StatusModel(models.Model):
	status = models.TextField() 
	time = models.DateTimeField(auto_now_add = True)
	def __str__(self):
		return self.status

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

status/forms.py
from django import forms
from .models import StatusModel

class StatusForm(forms.ModelForm):
	class Meta:
		model = StatusModel
		fields = ['status']
		widgets ={
		'status':forms.Textarea(attrs={'class':'form-control', 
										'placeholder': 'Masukkan kabar kamu hari ini :)'}),
		}

story7/forms.py
from django import forms
from status.models import StatusModel

class StatusForm(forms.ModelForm):
	class Meta:
		model = StatusModel
		fields = ['status']
		widgets ={
		'status':forms.Textarea(attrs={'class':'form-control', 
										'placeholder': 'Masukkan kabar kamu hari ini :)'}),
		}

story9/forms.py
from django import forms
from django.contrib.auth.models import User

class MakeUser(forms.ModelForm):
	konfirmasi_password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 
										}))
	class Meta():
		model = User
		fields = ('username', 'password', 'email')
		widgets ={
		'username':forms.TextInput(attrs={'class':'form-control', 
										}),
		'password':forms.PasswordInput(attrs={'class':'form-control', 
										}),
		'email':forms.EmailInput(attrs={'class':'form-control', 
										}),
		}

status/views.py
from django.shortcuts import render, redirect
from .models import StatusModel
from .forms import StatusForm
from django.utils import timezone
# Create your views here.
def add_status(request):
	if request.method =='POST':
		form = StatusForm(request.POST)
		if form.is_valid():
			if (len(form.cleaned_data['status']) < 301): # maksimal input status 300 char
				post = form.save(commit=False)
				post.time = timezone.now() 
				post.save()
				return redirect('/')
			else:
				return redirect('/')
	else:
		form = StatusForm()
	objects = StatusModel.objects.all()
	isi = {'generate_form': form,
			'all_objects':objects}
	return render(request,'status.html',isi)

story7/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from status.models import StatusModel
from status.forms import StatusForm
from django.utils import timezone
# Create your views here.
def addstatus(request):
	if request.method =='POST':
		form = StatusForm(request.POST)
		if form.is_valid():
			if (len(form.cleaned_data['status']) < 301): # maksimal input status 300 char
				post = form.save(commit=False)
				post.time = timezone.now() 
				post.save()
				return redirect('/storyke7/')
			else:
				return redirect('/storyke7/')
	else:
		form = StatusForm()
	objects = StatusModel.objects.all()
	isi = {'generate_form': form,
			'all_objects':objects}
	return render(request,'story7.html',isi)
# Create your views here.

story8/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import JsonResponse
import requests
# Create your views here.
def list_books(request):
	return render(request, 'story8.html')

def process_json(request, keyword):
	r = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + keyword)
	return JsonResponse(r.json())
	

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import MakeUser
from django.contrib.auth.models import User
def index(request):
	return render(request, 'index.html')

def user_login(request):
	if request.method == 'POST':
		username_input=request.POST['username']
		password_input=request.POST['password']
		user = authenticate(request, username=username_input, password=password_input)
		if user is not None:
			login(request, user)
			return redirect('/story9/')
		else:
			return render(request, 'login.html', {'error_message': 'Masukkan tidak valid.'})
	return render(request, 'login.html')

def register(request):
	if request.method =='POST':
		form = MakeUser(request.POST)
		if form.is_valid():
			if form.cleaned_data['password']!= form.cleaned_data['konfirmasi_password']:
				return render(request, 'register.html', {'form':form,
														'error_message':'Password tidak sama'})
			else:
				user = User.objects.create_user(
					form.cleaned_data['username'],
					form.cleaned_data['email'],
					form.cleaned_data['password']
					)
				user.save()
				return render(request, 'register.html', {
                    'form': form,
                    'message': 'Akun berhasil dibuat, Silahkan Login.'
                })
	else:
		form = MakeUser()
	isi = {'form': form,}
	return render(request, 'register.html', isi)

def user_logout(request):
	logout(request)
	return redirect('/story9')

status/templates/status.html
{% load staticfiles %} 
<!DOCTYPE html>
<html>
<head>
	<title>My Status</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/sheet.css' %}">
</head>
<body>
	<div class="container">
		<h2 class="title">Halo, Apa Kabar?</h2>
		<div class="all-form">
			<form action="{% url 'status:status' %}" method="POST" novalidate>{% csrf_token %}
					<div class="d-flex flex-column flex-md-row flex-wrap justify-content-md-center">
						<div class="form-group col-lg-2 col-form-label">
							<label class="text_right">Status</label>
						</div>
						<div class="form-group col-lg-10">
							{{generate_form.status}}
						</div>
					</div>
					<div class="d-flex flex-column flex-md-row flex-wrap justify-content-center">
						<div class="col-2">
							<button type="submit" class="btn btn-lg btn-light" name='simpan' value="Save">Simpan</button>
						</div>
					</div>
			</form>
		</div>
		<div class="data">
			<h2 class="text-center">Informasi Status Anda</h2>
			<table class="table table-responsive-md table-bordered">
	                <thead>
	                    <tr>
	                        <th scope="col">Waktu</th>
	                        <th scope="col">Status</th>
	                    </tr>
	                </thead>
	                <tbody>
	                	{% for obj in all_objects %}
	                    <tr>
	                        <td style="width:30%" >{{ obj.time}}</td>
	                        <td style="width:70%" >{{ obj.status}}</td>
	                    </tr> 
	                    {% endfor %}
	                </tbody>
	        </table>
		</div>
	</div>
</body>
</html>

story7/templates/story7.html
{% load staticfiles %} 
<!DOCTYPE html>
<html>
<head>
	<title>My Status</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style2.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
	<script src="{% static 'js/script.js' %}"></script>
</head>
<body>
	<div class="container">
		<h2 class="title">Halo, Apa Kabar?</h2>
		<div class="theme d-flex justify-content-end">
			<button id=button-theme class="btn btn-md btn-light" name="theme-btn" type="button">Ubah Tema</button>
		</div>
		<div class="all-form">
			<form action="{% url 'story7:status' %}" method="POST" novalidate>{% csrf_token %}
					<div class="d-flex flex-column flex-md-row flex-wrap justify-content-md-center">
						<div class="form-group col-lg-2 col-form-label">
							<label class="text_right">Status</label>
						</div>
						<div class="form-group col-lg-10">
							{{generate_form.status}}
						</div>
					</div>
					<div class="d-flex flex-column flex-md-row flex-wrap justify-content-center">
						<div class="col-2">
							<button type="submit" class="btn btn-lg btn-light" name='simpan' value="Save">Simpan</button>
						</div>
					</div>
			</form>
		</div>
		<div class="data">
			<h2 id=sub-title class="text-center">Informasi Status Anda</h2>
			<table class="table table-responsive-md table-bordered">
	                <thead>
	                    <tr>
	                        <th class= text-center scope="col">Waktu</th>
	                        <th class= text-center scope="col">Status</th>
	                    </tr>
	                </thead>
	                <tbody>
	                	{% for obj in all_objects %}
	                    <tr>
	                        <td style="width:30%" >{{ obj.time}}</td>
	                        <td style="width:70%" >{{ obj.status}}</td>
	                    </tr> 
	                    {% endfor %}
	                </tbody>
	        </table>
		</div>
		<div class="d-flex justify-content-center">
			<div id="accordion">
			<h5>Aktivitas</h5>
		  	<div class="isian">
		  		Kuliah<br>
		    	Ngantuk<br>
		   		Tidur<br>
		   		Pulang
		  	</div>
		  	<h5>Pengalaman Organisasi/Kepanitiaan</h5>
		  	<div class="isian">
		  		Sekretaris PMR 2017<br>
		    	FUKI Fasilkom UI 2018-2019
		  	</div>
		 	<h5>Prestasi</h5>
		  	<div class="isian">
		  		Coming Soon
		  	</div>
		</div>
		</div>
		
	</div>
</body>
</html>

story8/templates/story8.html
{% load staticfiles %} 
<!DOCTYPE html>
<html>
<head>
	<title>My Books</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style2.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static 'js/script8.js' %}"></script>
</head>
<body>
	<div class="container">
		<h2 class='title'>Halo, Mau Baca Buku?</h2>
		<div class="all-form d-flex flex-column flex-md-row flex-wrap justify-content-md-center">
			<div class="form-group col-lg-11 col-form-label">
				<input id='area-search' class="form-control" type="text"
                       placeholder="Ayo cari buku yang kamu mau">
			</div>
			<div class="form-group col-lg-1">
                    <button type="submit" class="btn btn-md btn-light" id="btn-search">Cari</button>
            </div>
        </div>
        <div class="data">
			<h2 id=sub-title class="text-center">Informasi Buku Anda</h2>
			<table class="table table-responsive-md table-bordered">
	                <thead>
	                    <tr>
	                    	<th style="width:4%" class= text-center scope="col">No.</th>
	                        <th style="width:24%" class= text-center scope="col">Cover Buku</th>
	                        <th style="width:24%" class= text-center scope="col">Judul Buku</th>
	                        <th style="width:24%" class= text-center scope="col">Penulis Buku</th>
	                        <th style="width:24%"class= text-center scope="col">Penerbit Buku</th>
	                    </tr>
	                </thead>
	                <tbody id=per-buku class="text-center">
	                </tbody>
	        </table>
		</div>
	</div>
</body>
</html>

story9/templates/index.html
{% load staticfiles %} 
<!DOCTYPE html>
<html>
<head>
	<title>My Books</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/story9.css' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static 'js/script8.js' %}"></script>
</head>
<body>
	<div class="container">
		<div class="row">
			<p class="col-lg-2 col-4 about"><a style="font-weight: bold;" href="{% url 'story9:index' %}">HOME</a></p>
			{% if user.is_authenticated %}
			<p class="col-lg-2 col-4 about"><a style="font-weight: bold;" href="{% url 'story9:logout' %}">LOGOUT</a></p>
			<h5 class="col-lg-3 col-8 about">Halo: {{user}}!</h5>
			{% else %}
			<p class="col-lg-2 col-4 about"><a style="font-weight: bold;" href="{% url 'story9:register' %}">REGISTER</a></p>
			<p class="col-lg-2 col-4 about"><a style="font-weight: bold;" href="{% url 'story9:login' %}">LOGIN</a></p>
			<h5 class="col-lg-3 col-8 about">Halo: Anonim, Ayo Log In!</h5>

			{% endif %}
		</div>
		
		<h2 class='title'>Halo, Mau Baca Buku?</h2>
		<div class="all-form d-flex flex-column flex-md-row flex-wrap justify-content-md-center">
			<div class="form-group col-lg-11 col-form-label">
				<input id='area-search' class="form-control" type="text"
                       placeholder="Ayo cari buku yang kamu mau">
			</div>
			<div class="form-group col-lg-1">
                    <button type="submit" class="btn btn-md btn-light" id="btn-search">Cari</button>
            </div>
        </div>
        <div class="data">
			<h2 id=sub-title class="text-center">Informasi Buku Anda</h2>
			<table class="table table-responsive-md table-bordered">
	                <thead>
	                    <tr>
	                    	<th style="width:4%" class= text-center scope="col">No.</th>
	                        <th style="width:24%" class= text-center scope="col">Cover Buku</th>
	                        <th style="width:24%" class= text-center scope="col">Judul Buku</th>
	                        <th style="width:24%" class= text-center scope="col">Penulis Buku</th>
	                        <th style="width:24%"class= text-center scope="col">Penerbit Buku</th>
	                    </tr>
	                </thead>
	                <tbody id=per-buku class="text-center">
	                </tbody>
	        </table>
		</div>
	</div>
</body>
</html>

story9/templates/login.html
{% load staticfiles %} 
<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/story9.css' %}">
</head>
<body>
	<div class="container">
		<p class="about"><a style="font-weight: bold;" href="{% url 'story9:index' %}">HOME</a></p>
		<h2 class="title">Halo, Ayo Log In!</h2>
		<div class="all-form ">
			<form method="POST">{% csrf_token %}
				<p class="about" style="text-align: center;">{{error_message}}</p>
				<div class="d-flex flex-column flex-md-row flex-wrap justify-content-md-center">
					<div class="form-group col-lg-3 col-form-label">
						<label>Username</label>						
					</div>
					<div class="form-group col-lg-5">
						<input type="text" class="form-control" name="username" required>
					</div>
				</div>	
				<div class="d-flex flex-column flex-md-row flex-wrap justify-content-md-center">	
					<div class="form-group col-lg-3 col-form-label">
						<label>Password</label>
					</div>
					<div class="form-group col-lg-5">
						<input type="password" class="form-control" name="password" required>
					</div>
				</div>
				<div class="d-flex flex-column flex-md-row flex-wrap justify-content-md-center">
					<input class="btn btn-light" type="submit" value="Log In!">
				</div>
			</form>	
		</div>
	</div>
</body>
</html>

story9/templates/register.html
{% load staticfiles %} 
<!DOCTYPE html>
<html>
<head>
	<title>Register</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/story9.css' %}">
</head>
<body>
	<div class="container">
		<p class="about"><a style="font-weight: bold;" href="{% url 'story9:index' %}">HOME</a></p>
		<h2 class="title">Halo, Ayo Register!</h2>
		<div class="all-form ">
			<form method="POST">{% csrf_token %}
				<p class="about" style="text-align: center;">{{error_message}}</p>
				<div class="d-flex flex-column flex-md-row flex-wrap justify-content-md-center">
					<div class="form-group col-lg-4 col-form-label">
						<label>Username</label>						
					</div>
					<div class="form-group col-lg-5">
						{{form.username}}
					</div>
				</div>
				<div class="d-flex flex-column flex-md-row flex-wrap justify-content-md-center">	
					<div class="form-group col-lg-4 col-form-label">
						<label>Email</label>
					</div>
					<div class="form-group col-lg-5">
						{{form.email}}
					</div>
				</div>	
				<div class="d-flex flex-column flex-md-row flex-wrap justify-content-md-center">
					<div class="form-group col-lg-4 col-form-label">
						<label>Password</label>
					</div>
					<div class="form-group col-lg-5">
						{{form.password}}
					</div>
				</div>
				<div class="d-flex flex-column flex-md-row flex-wrap justify-content-md-center">
					<div class="form-group col-lg-4 col-form-label">
						<label>Konfirmasi Password</label>
					</div>
					<div class="form-group col-lg-5">
						{{form.konfirmasi_password}}
					</div>
				</div>	
				<div class="d-flex flex-column flex-md-row flex-wrap justify-content-md-center">
					<input class="btn btn-light" type="submit" value="Register!">
				</div>
				<p class="about" style="text-align: center;">{{message}}</p>
			</form>	
		</div>
	</div>
</body>
</html>